import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import logo from '../public/assets/img/logo.png'
import {Grid, Icon} from "@mui/material";
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';


const MainApp = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div  className={styles.main}>
        <div item xs={6} className={styles.left}>
          <div className={styles.atas}>
            <img className={styles.logo} src='https://pbs.twimg.com/media/FE3pM9SVUAMmS-P?format=png&name=orig'/>
            <br/>
            <h1 className={styles.title}>Welcome to Lyrid</h1>
            <p className={styles.subtitle}>Get started by editing your Express Typescript App
              <br/>
              routes at src/entry/entry.ts
            </p>
          </div>
          <div className={styles.bawah}>
            <img className={styles.mascot} src='https://pbs.twimg.com/media/FE3pM9OVIAI0YiU?format=png&name=orig'/>
          </div>
        </div>
        <div item xs={6} className={styles.right}>
          <div className={styles.docsEx}>
            <a href="https://docs.lyrid.io" className={styles.boxRight}>
              <div className={styles.boxIsi}>
                <div className={styles.boxTitle}>
                  <h5 className={styles.docs}>Documentation <span><i></i></span></h5>
                  <img className={styles.arrow} src='https://pbs.twimg.com/media/FFX4V4gVQAEuJ_I?format=png&name=orig' />
                </div>
                <p className={styles.ex}>Find in-depth information about Node.js features and API.</p>
              </div>
            </a>
            <a href="https://github.com/LyridInc" className={styles.boxRight}>
              <div className={styles.boxIsi}>
                <div className={styles.boxTitle}>
                  <h5 className={styles.docs}>Examples <span><i></i></span></h5>
                  <img className={styles.arrow} src='https://pbs.twimg.com/media/FFX4V4gVQAEuJ_I?format=png&name=orig' />
                </div>
                <p className={styles.ex}>Discover and deploy boilerplate example Node.js projects.</p>
              </div>
            </a>
          </div>
        </div>
      </div>


    </div>
  )
};

export default MainApp;

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//
//       <main className={styles.main}>
//
//       </main>
//
//
//     </div>
//   )
// }
